version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: apt-get -y update; 
            apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev; 
            apt-get install -y software-properties-common; 
            add-apt-repository ppa:bitcoin/bitcoin;
            apt-get -y update;
            apt-get install -y libdb4.8-dev libdb4.8++-dev;
            apt-get install -y libminiupnpc-dev libzmq3-dev;
            apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev 
      - run:
          name: AUTOGEN
          command: ./autogen.sh
      - run:
          name: CONFIGURE
          command: ./configure
      - run:
          name: MAKE
          command: make -j4
