version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: AUTOGEN
          command: ./autogen.sh
      - run:
          name: CONFIGURE
          command: ./configure
      - run:
          name: MAKE
          command: make -j4
