version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: sudo apt-get update; sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev; sudo apt-get install software-properties-common; sudo add-apt-repository ppa:bitcoin/bitcoin;sudo apt-get update;sudo apt-get install libdb4.8-dev libdb4.8++-dev;sudo apt-get install libminiupnpc-dev libzmq3-dev;sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev 
      - run:
          name: AUTOGEN
          command: ./autogen.sh
      - run:
          name: CONFIGURE
          command: ./configure
      - run:
          name: MAKE
          command: make -j4
